"""
Creates a sample fillable PDF template for Swiss rental applications.
Run this script once to generate the template that fill_rental_pdf.py will fill.

Usage:
    python create_sample_template.py [output_path]
"""

import argparse
import sys

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.pdfbase.pdfform import (
    textFieldAbsolute,
    buttonFieldAbsolute,
)


FORM_FIELDS = [
    # (field_name, label, x, y, width, height)
    ("lastName",     "Last Name / Nachname",       4.5, 25.5, 7.0, 0.6),
    ("firstName",    "First Name / Vorname",        4.5, 24.3, 7.0, 0.6),
    ("dateOfBirth",  "Date of Birth / Geburtsdatum",4.5, 23.1, 4.0, 0.6),
    ("nationality",  "Nationality / Nationalität",  4.5, 21.9, 5.0, 0.6),
    ("maritalStatus","Marital Status / Zivilstand",  4.5, 20.7, 5.0, 0.6),
    ("currentAddress","Current Address / Adresse",  4.5, 19.5, 10.0, 0.6),
    ("zipCode",      "ZIP / PLZ",                   4.5, 18.3, 2.5, 0.6),
    ("city",         "City / Ort",                  4.5, 17.1, 7.0, 0.6),
    ("phone",        "Phone / Telefon",              4.5, 15.9, 5.0, 0.6),
    ("email",        "Email / E-Mail",               4.5, 14.7, 8.0, 0.6),
    ("employer",     "Employer / Arbeitgeber",       4.5, 13.5, 8.0, 0.6),
    ("occupation",   "Occupation / Beruf",           4.5, 12.3, 7.0, 0.6),
    ("annualIncome", "Annual Income CHF / Jahreseinkommen CHF", 4.5, 11.1, 4.0, 0.6),
    ("numPersons",   "No. of Persons / Anzahl Personen", 4.5, 9.9, 2.5, 0.6),
    ("hasPets",      "Pets / Haustiere (Yes/No)",    4.5, 8.7, 2.5, 0.6),
    ("moveInDate",   "Desired Move-in / Einzugsdatum", 4.5, 7.5, 4.0, 0.6),
    ("numCars",      "No. of Cars / Anzahl Autos",   4.5, 6.3, 2.5, 0.6),
    ("aiSummary",    "AI Cover Letter / KI-Anschreiben", 4.5, 3.0, 13.0, 2.8),
]


def create_template(output_path: str = "rental_application_template.pdf") -> None:
    """Create a fillable PDF template for a Swiss rental application."""
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2 * cm, height - 2 * cm, "Swiss Rental Application / Mietbewerbung")

    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawString(2 * cm, height - 2.6 * cm, "Please fill in all fields. / Bitte alle Felder ausfüllen.")
    c.setFillColorRGB(0, 0, 0)

    # Draw labels and form fields
    c.setFont("Helvetica", 9)
    for field_name, label, x, y, w, h in FORM_FIELDS:
        x_pt = x * cm
        y_pt = y * cm
        w_pt = w * cm
        h_pt = h * cm

        # Draw label above the field
        c.setFont("Helvetica", 8)
        c.setFillColorRGB(0.3, 0.3, 0.3)
        c.drawString(x_pt, y_pt + h_pt + 2, label)
        c.setFillColorRGB(0, 0, 0)

        # Draw text input field
        if field_name == "aiSummary":
            # Multi-line field for the AI summary
            c.acroForm.textfield(
                name=field_name,
                tooltip=label,
                x=x_pt,
                y=y_pt,
                width=w_pt,
                height=h_pt,
                fontSize=8,
                fieldFlags="multiline",
                borderStyle="inset",
            )
        else:
            c.acroForm.textfield(
                name=field_name,
                tooltip=label,
                x=x_pt,
                y=y_pt,
                width=w_pt,
                height=h_pt,
                fontSize=9,
                borderStyle="inset",
            )

    # Divider line before AI section
    c.setStrokeColorRGB(0.7, 0.7, 0.7)
    c.line(2 * cm, 5.8 * cm, (width - 2 * cm), 5.8 * cm)

    c.setFont("Helvetica-BoldOblique", 8)
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.drawString(2 * cm, 5.5 * cm, "AI-generated introduction (powered by local Ollama)")
    c.setFillColorRGB(0, 0, 0)

    # Footer
    c.setFont("Helvetica", 7)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(2 * cm, 1.2 * cm,
                 "Generated by rental_application script  •  github.com/rbalebako/rental_application")

    c.save()
    print(f"Template created: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a sample fillable PDF template for Swiss rental applications"
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="rental_application_template.pdf",
        help="Output path for the template PDF (default: rental_application_template.pdf)",
    )
    args = parser.parse_args()
    create_template(args.output)


if __name__ == "__main__":
    main()
